---
- name: Install S3 upload script
  template:
    src: 'upload-to-s3.p2'
    dest: '/usr/local/bin/upload-to-s3'
    mode: 0750

- name: Sync build options from S3
  shell: |
    export AWS_ACCESS_KEY_ID='{{ aws_access_key_id }}'
    export AWS_SECRET_ACCESS_KEY='{{ aws_secret_access_key }}'
    export AWS_DEFAULT_REGION='{{ aws_default_region }}'
    /usr/local/bin/aws s3 sync \
      s3://{{ s3_bucket_name }}{{ s3_upload_path }}/build-options/ \
      {{ poudriere_config_path }}/
  args:
    executable: /bin/sh
  when: s3_bucket_name | length > 0
