---
- name: Install required packages
  pkgng: name={{ item }}
         state=present
  with_items:
  - poudriere
  - dialog4ports
  - py27-pip

- name: Create directory for ssl key
  file: path={{ poudriere_ssl_prefix }}
        state=directory

- name: Copy sign key
  copy: src={{ poudriere_key_file }}
        dest={{ poudriere_ssl_prefix }}/poudriere.key
        mode=0600

- name: Create poudriere.conf
  template: src=poudriere.conf.p2
            dest=/usr/local/etc/poudriere.conf

- name: Create missing distfile directory
  file: path=/usr/ports/distfiles
        state=directory

- name: Create poudriere jails
  command: poudriere jail -c -j {{ item.jail_name }} -v {{ item.version }}
           creates={{ poudriere_config_path }}/jails/{{ item.jail_name }}/timestamp
  with_items: '{{ poudriere_jails }}'

- name: Copy make.conf
  copy: src={{ poudriere_build_options_file }}
        dest={{ poudriere_config_path }}/{{ item.jail_name }}-make.conf
  with_items: '{{ poudriere_jails }}'

- name: Copy list of packages to build
  copy: src={{ poudriere_port_list_file }}
        dest={{ poudriere_config_path }}/port-list

- name: Download most recent ports tree
  command: poudriere ports -c -p HEAD
           creates=/usr/local/poudriere/ports/HEAD

- name: Install build script
  template: src=build-ports.p2
            dest=/usr/local/bin/build-ports
            mode=0750

- name: Enable daily build cron job
  cron:
    name: Run poudriere build
    job: /usr/local/bin/build-ports -y
    special_time: daily
  when: poudriere_enable_cron

- include: aws_s3.yml
  when: poudriere_enable_s3
